//
//  LinearParser.swift
//  Covfefe
//
//  Created by Palle Klewitz on 15.08.17.
//

import Foundation

/// A parser for linear grammars
///
/// Linear grammars can be described by linear productions:
///
///     A -> x B y
///     A -> z
public class LinearParser {
	
	/// Grammar parsed by the parser
	public let grammar: Grammar
	
	/// Creates a new parser for linear grammars.
	///
	/// The specified grammar has to be linear for this parser to work.
	/// All productions must have the form
	///
	///     A -> x B y
	///     A -> z
	///
	/// - Parameter grammar: Recognized grammar
	public init(grammar: Grammar) {
		assert(grammar.productions.allMatch{$0.isLinear}, "LinearParser can only recognize linear grammars.")
		self.grammar = grammar
	}
	
	/// Returns true if the recognized language contains the given word.
	///
	/// - Parameter word: Word which should be checked
	/// - Returns: True, if the word is generated by the grammar, false if not.
	public func recognizes(word: String) -> Bool {
		let nonTerminalProductions = Dictionary(grouping: grammar.productions, by: {$0.pattern})
		func contains(word: String, startingAt start: NonTerminal) -> Bool {
			let possibleProductions = nonTerminalProductions[start, default: []].filter {$0.canGenerateSubstring(of: word)}
			
			return possibleProductions.contains { production -> Bool in
				if production.canFullyGenerate(word: word) {
					return true
				}
				let unexplainedSubstring = production.removingGeneratedSubstring(from: word)
				guard let nonTerminal = production.generatedNonTerminals.first else {
					return false
				}
				return contains(word: unexplainedSubstring, startingAt: nonTerminal)
			}
		}
		
		return contains(word: word, startingAt: grammar.start)
	}
	
	/// Creates a string describing how the given word was produced
	///
	/// - Parameter word: Input word
	/// - Returns: A string explaining how the string was derived by the recognized grammar
	public func syntaxTree(for word: String) -> String? {
		let nonTerminalProductions = Dictionary(grouping: grammar.productions, by: {$0.pattern})
		func explain(word: String, startingAt start: NonTerminal) -> String? {
			let possibleProductions = nonTerminalProductions[start, default: []].filter {$0.canGenerateSubstring(of: word)}
			
			return possibleProductions.flatMap { production -> String? in
				if production.canFullyGenerate(word: word) {
					return production.pattern.name
				}
				let unexplainedSubstring = production.removingGeneratedSubstring(from: word)
				guard let nonTerminal = production.generatedNonTerminals.first else {
					return nil
				}
				guard let substringExplanation = explain(word: unexplainedSubstring, startingAt: nonTerminal) else {
					return nil
				}
				return "\(start.name) --> \(substringExplanation)"
			}.first
		}
		
		return explain(word: word, startingAt: grammar.start)
	}
}
