//
//  SyntaxTree.swift
//  Covfefe
//
//  Created by Palle Klewitz on 07.08.17.
//  Copyright (c) 2017 Palle Klewitz
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.

import Foundation

/// A tree which can store different types of values in its leafs
///
/// - leaf: A leaf
/// - node: A node with a key and an arbitrary list of elements
public enum SyntaxTree<Element, LeafElement> {
	/// A leaf storing a leaf element
	case leaf(LeafElement)
	
	/// A node with a key and an arbitrary list of elements
	indirect case node(key: Element, children: [SyntaxTree<Element, LeafElement>])
}

public extension SyntaxTree {
	
	/// Generates a new syntax tree by applying the transform function to every key of the tree
	///
	/// - Parameter transform: Transform function
	/// - Returns: A tree generated by applying the transform function to every key
	func map<Result>(_ transform: (Element) throws -> Result) rethrows -> SyntaxTree<Result, LeafElement> {
		switch self {
		case .leaf(let leaf):
			return .leaf(leaf)
			
		case .node(key: let key, children: let children):
			return try .node(key: transform(key), children: children.map{try $0.map(transform)})
		}
	}
	
	/// Generates a new syntax tree by applying the transform function to every leaf of the tree
	///
	/// - Parameter transform: Transform function
	/// - Returns: A tree generated by applying the transform function to every leaf value
	func mapLeafs<Result>(_ transform: (LeafElement) throws -> Result) rethrows -> SyntaxTree<Element, Result> {
		switch self {
		case .leaf(let leaf):
			return try .leaf(transform(leaf))
			
		case .node(key: let key, children: let children):
			return try .node(key: key, children: children.map{try $0.mapLeafs(transform)})
		}
	}
	
	/// All leafs of the tree
	var leafs: [LeafElement] {
		switch self {
		case .leaf(let leaf):
			return [leaf]
			
		case .node(key: _, children: let children):
			return children.flatMap{$0.leafs}
		}
	}
	
	/// Filters the tree by removing all nodes and their corresponding subtrees if the given predicate is false
	///
	/// - Parameter predicate: Predicate to filter the tree
	/// - Returns: A tree generated by filtering out nodes for which the predicate returned false
	func filter(_ predicate: (Element) throws -> Bool) rethrows -> SyntaxTree<Element, LeafElement>? {
		switch self {
		case .leaf(let element):
			return .leaf(element)
			
		case .node(key: let key, children: let children) where try predicate(key):
			return try .node(key: key, children: children.compactMap{try $0.filter(predicate)})
			
		case .node(key: _, children: _):
			return nil
		}
	}
	
	/// Explodes nodes and passes all child nodes to the parent node if the given closure returns true
	///
	/// - Parameter shouldExplode: Determines if a node should be exploded
	/// - Returns: A tree generated by exploding nodes determined by the given predicate
	func explode(_ shouldExplode: (Element) throws -> Bool) rethrows -> [SyntaxTree<Element, LeafElement>] {
		switch self {
		case .leaf:
			return [self]
			
		case .node(key: let key, children: let children) where try shouldExplode(key):
			return try children.flatMap{try $0.explode(shouldExplode)}
			
		case .node(key: let key, children: let children):
			return try [.node(key: key, children: children.flatMap{try $0.explode(shouldExplode)})]
		}
	}
	
	/// Compresses the tree by exploding nodes which have exactly one child node
	///
	/// - Returns: Tree generated by compressing the current tree
	func compressed() -> SyntaxTree<Element, LeafElement> {
		switch self {
		case .node(key: _, children: let children) where children.count == 1:
			let child = children[0]
			if case .leaf = child {
				return self
			} else {
				return child.compressed()
			}
			
		case .node(key: let key, children: let children):
			return .node(key: key, children: children.map{$0.compressed()})
			
		default:
			return self
		}
	}
	
	/// Returns all nodes which match the given predicate.
	///
	///
	/// - Parameter predicate: Predicate to match
	/// - Returns: A collection of nodes which match the given predicate
	func allNodes(where predicate: (Element) throws -> Bool) rethrows -> [SyntaxTree<Element, LeafElement>] {
		switch self {
		case .leaf:
			return []
			
		case .node(key: let key, children: let children) where try predicate(key):
			return try [self] + children.flatMap{try $0.allNodes(where: predicate)}
			
		case .node(key: _, children: let children):
			return try children.flatMap{try $0.allNodes(where: predicate)}
		}
	}
	
	
}

extension SyntaxTree: CustomDebugStringConvertible {
	public var debugDescription: String {
		switch self {
		case .leaf(let value):
			return "leaf (value: \(value))"
			
		case .node(key: let key, children: let children):
			let childrenDescription = children.map{$0.debugDescription}.joined(separator: "\n").replacingOccurrences(of: "\n", with: "\n\t")
			return """
			node (key: \(key)) {
				\(childrenDescription)
			}
			"""
		}
	}
}

extension SyntaxTree: CustomStringConvertible {
	public var description: String {
		var id = 0
		let uniqueKeyTree = self.map { element -> (Int, Element) in
			let uniqueElement = (id, element)
			id += 1
			return uniqueElement
		}.mapLeafs { leaf -> (Int, LeafElement) in
			let uniqueLeaf = (id, leaf)
			id += 1
			return uniqueLeaf
		}
		
		
		func generateDescription(_ tree: SyntaxTree<(Int, Element), (Int, LeafElement)>) -> String {
			switch tree {
			case .leaf(let leaf):
				let (id, leafElement) = leaf
                let leafDescription = "\(leafElement)"
                    .literalEscaped
                    .replacingOccurrences(of: "\"", with: "\\\"")
				return "node\(id) [label=\"\(leafDescription)\" shape=box]"
				
			case .node(key: let key, children: let children):
				let (id, element) = key
				let childrenDescriptions = children.map(generateDescription).filter{!$0.isEmpty}.joined(separator: "\n")
				let childrenPointers = children.compactMap{ node -> Int? in
					if let id = node.root?.0 {
						return id
					} else if let id = node.leaf?.0 {
						return id
					} else {
						return nil
					}
				}.map{"node\(id) -> node\($0)"}.joined(separator: "\n")
				
				var result = "node\(id) [label=\"\(element)\"]"
				if !childrenPointers.isEmpty {
					result += "\n\(childrenPointers)"
				}
				if !childrenDescriptions.isEmpty {
					result += "\n\(childrenDescriptions)"
				}
				
				return result
			}
		}
		
		func allLeafIDs(_ tree: SyntaxTree<(Int, Element), (Int, LeafElement)>) -> [Int] {
			switch tree {
			case .leaf(let leaf):
				return [leaf.0]
				
			case .node(key: _, children: let children):
				return children.flatMap(allLeafIDs)
			}
		}
		
		return """
		digraph {
			\(generateDescription(uniqueKeyTree).replacingOccurrences(of: "\n", with: "\n\t"))
			{
				rank = same
				\(allLeafIDs(uniqueKeyTree).map(String.init).map{"node\($0)"}.joined(separator: "\n\t\t"))
			}
		}
		"""
	}
}

/// Determines if two syntax trees are equal to each other.
///
/// This function returns true, if both trees have the same structure, equal keys in equal nodes and equal leafs
///
/// - Parameters:
///   - lhs: First tree to compare
///   - rhs: Second tree to compare
/// - Returns: A boolean value indicating whether the provided trees are equal to each other
public func == <Element: Equatable, LeafElement: Equatable>(lhs: SyntaxTree<Element, LeafElement>, rhs: SyntaxTree<Element, LeafElement>) -> Bool {
	switch (lhs, rhs) {
	case (.leaf, .leaf):
		return true
		
	case (.node(key: let lKey, children: let lChildren), .node(key: let rKey, children: let rChildren)):
		return lKey == rKey && lChildren.count == rChildren.count && !zip(lChildren, rChildren).map(==).contains(false)
		
	default:
		return false
	}
}

public extension SyntaxTree {
	
	/// Creates a new syntax tree node with a given key and a list of children
	///
	/// - Parameters:
	///   - key: Root key
	///   - children: Children of the root node
	init(key: Element, children: [SyntaxTree<Element, LeafElement>]) {
		self = .node(key: key, children: children)
	}
	
	/// Creates a new syntax tree with a given root key and no children
	///
	/// - Parameter key: Root key
	init(key: Element) {
		self = .node(key: key, children: [])
	}
	
	/// Creates a new syntax tree with a given leaf value
	///
	/// - Parameter value: Leaf value
	init(value: LeafElement) {
		self = .leaf(value)
	}
}

public extension SyntaxTree where LeafElement == () {
	/// Creates an empty tree
	init() {
		self = .leaf(())
	}
}

public extension SyntaxTree {
	
	/// Returns the root key of the tree or nil if no root key exists
	var root: Element? {
		guard case .node(key: let root, children: _) = self else {
			return nil
		}
		return root
	}
	
	/// Returns the value stored in the current node if the current node is a leaf. Otherwise, nil is returned
	var leaf: LeafElement? {
		guard case .leaf(let leaf) = self else {
			return nil
		}
		return leaf
	}
	
	/// Returns the direct children of the root node
	var children: [SyntaxTree<Element, LeafElement>]? {
		switch self {
		case .leaf:
			return nil
			
		case .node(key: _, children: let children):
			return children
		}
	}
}
